/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.theveganrobot.OpenASURF.swig;

public class CvPoint {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	public CvPoint(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	public static long getCPtr(CvPoint obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				surfjnimoduleJNI.delete_CvPoint(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setX(int value) {
		surfjnimoduleJNI.CvPoint_x_set(swigCPtr, this, value);
	}

	public int getX() {
		return surfjnimoduleJNI.CvPoint_x_get(swigCPtr, this);
	}

	public void setY(int value) {
		surfjnimoduleJNI.CvPoint_y_set(swigCPtr, this, value);
	}

	public int getY() {
		return surfjnimoduleJNI.CvPoint_y_get(swigCPtr, this);
	}

	public CvPoint() {
		this(surfjnimoduleJNI.new_CvPoint(), true);
	}

}
