/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.theveganrobot.OpenASURF.swig;

public class surfjnimodule {
	public static CvPoint new_cvpointArray(int nelements) {
		long cPtr = surfjnimoduleJNI.new_cvpointArray(nelements);
		return (cPtr == 0) ? null : new CvPoint(cPtr, false);
	}

	public static void delete_cvpointArray(CvPoint ary) {
		surfjnimoduleJNI.delete_cvpointArray(CvPoint.getCPtr(ary), ary);
	}

	public static CvPoint cvpointArray_getitem(CvPoint ary, int index) {
		return new CvPoint(surfjnimoduleJNI.cvpointArray_getitem(
				CvPoint.getCPtr(ary), ary, index), true);
	}

	public static void cvpointArray_setitem(CvPoint ary, int index,
			CvPoint value) {
		surfjnimoduleJNI.cvpointArray_setitem(CvPoint.getCPtr(ary), ary, index,
				CvPoint.getCPtr(value), value);
	}

	public static void getMatches(IpointVector ipts1, IpointVector ipts2,
			IpPairVector matches) {
		surfjnimoduleJNI.getMatches(IpointVector.getCPtr(ipts1), ipts1,
				IpointVector.getCPtr(ipts2), ipts2,
				IpPairVector.getCPtr(matches), matches);
	}

	public static int translateCorners(IpPairVector matches,
			CvPoint src_corners, CvPoint dst_corners) {
		return surfjnimoduleJNI.translateCorners(IpPairVector.getCPtr(matches),
				matches, CvPoint.getCPtr(src_corners), src_corners,
				CvPoint.getCPtr(dst_corners), dst_corners);
	}

	public static SWIGTYPE_p_IplImage loadPixels(int[] pixels, int width,
			int height) {
		long cPtr = surfjnimoduleJNI.loadPixels(pixels, width, height);
		return (cPtr == 0) ? null : new SWIGTYPE_p_IplImage(cPtr, false);
	}

}
